baseurl      = "https://questionable-beta.com"
title        = "Questionable Beta"
languageCode = "en-us"
theme        = "hello-4s3ti"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  # Google Maps API
  googleMapsAPIKey = "AIzaSyA_ZxOA57_Ccb_v7d1-rxZ5eMsXAg90y6o"

  # Google Analytics 4
  GoogleAnalyticsID = "G-DNTW6BGD17"

  # Home page title
  homeTitle = "Questionable Beta"

  # Home subtitle of the index page.
  homeSubtitle = "\"Just go up\""
  
  # Adds a dark overlay over the background
  backgroundEffects = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  
  # Sets the default theme
  defaultTheme = "dark"

  # Enable theme toggle
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "A personal blog about climbing and other such stuff."
  keywords = "homepage, blog, climbing, bouldering, blogging, writing, personal"
  images = [""]

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  # 
  enableSharingButtons = true

  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = true

  # Shows Posts on the front/Home page
  showPosts = true

  # Shows the ReadMore button in text instead
  ReadmoreText = true

  # Hides ReadMore
  hideReadMore = true

  # Shows reding time
  ShowReadingTime = false
  
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.fontAwesome]
    KitURL = "https://kit.fontawesome.com/492096f227.js"

  [params.footer]
    trademark = false
    rss = false
    copyright = false
    author = false

    # Shows social icons on footer instead of main page
    socialIcons = true

    topText = []
    bottomText = ["Made with üêù by <b>Andy</b>"]


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "?Œ≤"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "?Œ≤"
      logoHomeLink = "/"
      logoCursorColor    = "#67a2c9"
      logoCursorAnimate  = "2s"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 10

  [[menu.main]]
    identifier = "gallery"
    name       = "Gallery"
    url        = "photos/"
    weight     = 10